// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  "https://ahqqptrclqtwqjgmtesv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocXFwdHJjbHF0d3FqZ210ZXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDM3NTMsImV4cCI6MjA2OTkxOTc1M30.FRFHf-XvnBLzZvcGseS82HJIORQXs_8OEEVq0RpabN0";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase environment variables not found, using fallback values",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a single shared Supabase client instance to prevent multiple GoTrueClient instances
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    // Disable realtime by default to prevent issues - can be enabled per subscription if needed
    realtime: {
      params: {
        eventsPerSecond: 0, // Disable realtime events
      },
      heartbeatIntervalMs: 60000,
      reconnectAfterMs: () => 10000,
    },
    global: {
      headers: {
        'X-Client-Info': 'helldivers2-boost-app-unified',
      },
    },
  },
);
